name: Deploy to ECR

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    
    env:
     ECR_REPO_PREFIX: assignment1-dev
     IMAGE_TAG: v1.0
   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1       

      # Runs a set of commands using the runners shell   
    - name: App Build, test, tag, and push image to Amazon ECR
      env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          cd clo835_fall2022_assignment1/  
          ls -ltra
          # Docker build
          docker build -t $ECR_REGISTRY/$ECR_REPO_PREFIX-app:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX-app:$IMAGE_TAG
          
    - name: MySQL DB build, test, tag, and push image to Amazon ECR
      env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          cd clo835_fall2022_assignment1/  
          ls -ltra
          # Docker build
          docker build -f Dockerfile_mysql -t $ECR_REGISTRY/$ECR_REPO_PREFIX-db:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX-db:$IMAGE_TAG

